home_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "Base_Namespace"	# The application namespace-- give the same name as application
urlpatterns = [
	url(r'^$', views.Home, name="Base_Home_View"),
	url(r'^about/', views.About, name="Base_About_View"),
	url(r'^account/', include('accounts_app.urls', namespace="Accounts_Namespace")), 	# All urls defined in accounts_app.urls are a part of the application namespace of whatever the app_name variable is defined to within that url file. The namespace specified here, should be the same name as the app_name of the url file you're linking to
	url(r'^admin/', admin.site.urls),
	url(r'^blog/', include('posts_app.urls', namespace="Posts_Namespace")),
	url(r'^sports/', views.Sports, name="Base_Sports_View"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'Posts_Namespace'
urlpatterns = [
	url(r'^$', views.Post_List, name="Posts_List"),
	url(r'^(?P<id>\d+)/$', views.Post_Detail, name="Posts_Detail"), # {% url "Post_Detail" id=obj.id %}
	url(r'^create$', views.Post_Create, name="Posts_Create"),
	url(r'^update$', views.Post_Update, name="Posts_Update"),
	url(r'^delete$', views.Post_Delete, name="Posts_Delete"),
]

home_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from accounts_app.forms import RegistrationForm

def About(request):
	template_name = 'About.html'
	return render(request, template_name)
def Blog(request):
	template_name = 'Blog.html'
	return render(request, template_name)
def Home(request):
	form_class = RegistrationForm
	template_name = 'Home.html'
	return render(request, template_name, {'form': form_class})
def Sports(request):
	pass

home_app/templates/About.html
{% extends "base.html" %}
{% load staticfiles %}
	{% block head %}
  	<link type="text/css" rel="stylesheet" href="{% static 'Stylesheets/Base.css' %}">
  	<link rel="stylesheet" type="text/css" href="{% static 'Stylesheets/About.css' %}">
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% endblock %}
	{% block main %}
    <section class="Container">
    	<section class="Main-Content">
        	<div class="Banner-Wrapper">
          		<div class="Banner-Background"></div>
          		<h3 class="Banner-Text">About</h3>
        	</div>
			<div class="Carousel-Container">
			    <form>
			      	<input type="radio" id="Slide-1-Button" class="Radio-Buttons" name="slider" title="Our Mission" autofocus="autofocus" checked="checked"/>
			      	<input type="radio" id="Slide-2-Button" class="Radio-Buttons" name="slider" title="Meet The Team"/>
			      	<div class="Slides-Container">
	            		<label for="Slide-1-Button" id="Slide-1-Label" class="Slide" style="background-color: #07152d";>
			          		<div class="content">
			            		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					        	<div></div>
			          		</div>
	            		</label>
			        	<label for="Slide-2-Button" id="Slide-2-Label" class="Slide">
			          		<div class="content">
			                    <div class="Team-Carousel">
			                      	<div id="left-arrow" class="arrow"></div>
				                          <div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>John Doe</h5>
				                            <h6>HTML Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>John Doe</h5>
				                            <h6>CSS Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>John Doe</h5>
				                            <h6>JavaScript Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>John Doe</h5>
				                            <h6>jQuery Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>Bob Ross</h5>
				                            <h6>Finger Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>Bob Ross</h5>
				                            <h6>Foot Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>Bob Ross</h5>
				                            <h6>Hair Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>Bob Ross</h5>
				                            <h6>Teeth Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>Bob Ross</h5>
				                            <h6>Finger Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div><div class="Card">
				                            <div class="Headshot"></div>
				                            <h5>Bob Ross</h5>
				                            <h6>Foot Specialist</h6>
				                            <p>John Doe is a html magician and he is just so amazing. no one can compete</p>
				                          </div>
			                      	<div id="right-arrow" class="arrow"></div>
			                    </div>
			                </div>
			        	</label>
			     	</form>
  				</div>
			</div>
      </section>
  </section>
  {% endblock %}
  {% block scripts %}
  <script type="text/javascript" src="{% static 'Scripts/About.js' %}"></script>
  {% endblock %}

home_app/templates/Blog.html
{% extends "base.html" %}
{% load staticfiles %}

	{% block head %}
    <link type="text/css" rel="stylesheet" href="{% static 'Stylesheets/Blog.css'%}">
    <link type="text/css" rel="stylesheet" href="{% static 'Stylesheets/Base.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% endblock %}


	{% block main %}
    <section class="Container">
        <section class="Main-Content">
          <div class="Banner-Wrapper">
            <div class="Banner-Background"></div>
            <h3 class="Banner-Text">Blog</h3>
          </div>
          	<ul class="Tiles">
				{% for post in post_objects %}
					<li class="Tile">
		              <!--<img src="{{ post.thumbnail.url }}"/>-->
					  <img src="{% static 'Images/Thumbnails/all-sports.jpg'%}"/>
		              <p class="Tile-Date">{{ post.timestamp }}</p>
		              <h3 class="Tile-Title">{{ post.title }}</h3>
		              <p class="Tile-Read-More"><a href="#">READ MORE</a></p>
					</li>
				{% endfor %}
			</ul>
          <div class="Button-Wrapper">
            <button type="button" value="prev_page" class="Directional-Button">P</button>
          	<button type="button" class="Number-Button Active">1</button>
          	<button type="button" class="Number-Button">2</button>
          	<button type="button" class="Number-Button">3</button>
          	<button type="button" class="Number-Button">4</button>
            <button type="button" value="next_page" class="Directional-Button">N</button>
          </div>
        </section>
    </section>
	{% endblock %}

home_app/templates/Home.html
{% extends "base.html" %}
{% load staticfiles %}
	{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'Stylesheets/Home.css' %}"/>
	<link type="text/css" rel="stylesheet" href="{% static 'Stylesheets/Base.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% endblock %}

	{% block main %}
	<section class="Container">
		<section class="Main-Content">
			<div class="Background-Image-Container"></div>
			<div class="Banner-Quote-Wrapper">
				<p class="Banner-Quote">Join the HIGHLIGHTPAGE family and get the</p>
				<p class="Banner-Quote">exposure needed to earn an atheletic scholarship.</p>
			</div>
			<div class="Credentials">
				<div class="Register-Screen-Wrapper"></div>
				<div class="Button-Wrapper">
					<button onclick="showPanel(0,'#509b65')">Sign Up</button>
					<button onclick="showPanel(1,'#1B59A5')">Log In</button>
				</div>
				<div class="Form-Wrapper">
					<div class="Tab-Panel" id="tab-1">
						<p class="Registry-Quote">Your BIG opportunity may be right</p>
						<p class="Registry-Quote">where you are now.</p>
						<form class="Registry-Form" action="account/" method="POST">
							{% csrf_token %}
							<label for="registry-first-name" class="Form-Half">First Name*</label>
							<label for="registry-last-name" class="Form-Half">Last Name*</label>
								{{ form.first_name }}
								{{ form.last_name }}
							<label for="registry-username" class="Form-Half">Username*</label>
							<label for="registry-occupation" class="Form-Half">Occupation*</label>
								{{ form.username }}
								{{ form.occupation }}
							<label for="registry-email" class="Form-Half">Email*</label>
								{{ form.email }}
							<label for="registry-password1" class="Form-Half">Password*</label>
							<label for="registry-password2" class="Form-Half">Confirm Password*</label>
								{{ form.password1 }}
								{{ form.password2 }}
							<button type="submit" name="registry_submit" class="Form-Button" id="register-button">Register</button>
						</form>
					</div>
					<div class="Tab-Panel" id="tab-2">
						<form class="Login-Form" action="account/login/" method="post">
							{% csrf_token %}
							<h2 class="Login-Quote">Welcome Back!</h2>
								<label class="Form-Full" for="login-username">Username*</span></label>
									<input type="text" class="Form-Half" name="login-username" id="login-username">
								<label class="Form-Full" for="login-password">Password*</label>
									<input type='password' class="Form-Half" name="login-password" id="login-password" maxlength="16" placeholder='Please enter your password'>
							<p class="Login-Forgot"><a href="#">Forgot your password?</a></p>
							<button type="submit" name="login_submit" class="Form-Button" id="login-button">Login</button>
						</form>
					</div>
				</div>
			</div>
		</section>
	</section>
	{% endblock %}
	{% block scripts %}
	<script type="text/javascript" src="{% static 'Scripts/Home.js' %}"></script>
	{% endblock %}

home_app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
	{% block head %}
	{% endblock %}
	</head>
	<body>
		<header class="Navigation">
			<div class="Logo" onclick="location.href='{% url 'Base_Home_View'%}'"></div>
			<ul class="Nav-Links">
				<li><a href="{% url 'Base_Home_View' %}" class="Active">Home</a></li>
				<li><a href="{% url 'Base_About_View' %}">About</a></li>
				<li><a href="{% url 'Base_Sports_View' %}">Sports</a></li>
				<li><a href="{% url 'Posts_Namespace:Posts_List' %}">Blog</a></li>
			</ul>
			<div class="Search-Wrapper">
				<input type="text" class="Search-Bar" placeholder="Search">
				<button type="submit" class="Search-Button">
					<i class="fa fa-search"></i>
				</button>
			</div>
			<div class="Color-Bar"></div>
		</header>
		{% block main %}
		{% endblock %}
		<footer>
			<div class="Bottom-Banner">
				<p>#169 2017 All Rights Reserved Terms of Use and Privacy Policy</p>
				<p>CONTACT US <span>placeholderemail@highlightpage.com</span></p>
				<p>FOLLOW US</p>
				<ul id="contact-icons">
					<div id="facebook" class="Crop-Circle" onclick="location.href='#'"></div>
					<div id="twitter" class="Crop-Circle" onclick="location.href='#'"></div>
					<div id="linkedin" class="Crop-Circle" onclick="location.href='#'"></div>
					<div id="googleplus" class="Crop-Circle" onclick="location.href='#'"></div>
					<div id="youtube" class="Crop-Circle" onclick="location.href='#'"></div>
				</ul>
			</div>
		</footer>
		{% block scripts %}
		{% endblock %}
	</body>
</html>